collections:
    
  ##################################################
  # Random Unwatched Movies
  ##################################################

  Random Unwatched Movies*:
    sort_title: "!015_Random Unwatched Movies"
    plex_search:
      all:
        unplayed: true
      sort_by: random
      limit: 100
    sync_mode: sync
    collection_mode: hide
    collection_order: custom
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/random-unwatched-movies.png

  ##################################################
  # Decades
  ##################################################

  #1910s:
    #sort_title: "!100_1910s"
    #sync_mode: sync
    #collection_mode: hide
    #collection_order: release
    #url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/1910s.png
    #plex_search:
      #year.gte: 1910
      #year.lte: 1919

  #1920s:
    #sort_title: "!100_1920s"
    #sync_mode: sync
    #collection_mode: hide
    #collection_order: release
    #url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/1920s.png
    #plex_search:
      #year.gte: 1920
      #year.lte: 1929

  #1930s:
    #sort_title: "!100_1930s"
    #sync_mode: sync
    #collection_mode: hide
    #collection_order: release
    #url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/1930s.png
    #plex_search:
      #year.gte: 1930
      #year.lte: 1939

  #1940s:
    #sort_title: "!100_1940s"
    #sync_mode: sync
    #collection_mode: hide
    #collection_order: release
    #url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/1940s.png
    #plex_search:
      #year.gte: 1940
      #year.lte: 1949

  #1950s:
    #sort_title: "!100_1950s"
    #sync_mode: sync
    #collection_mode: hide
    #collection_order: release
    #url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/1950s.png
    #plex_search:
      #year.gte: 1950
      #year.lte: 1959

  #1960s:
    #sort_title: "!100_1960s"
    #sync_mode: sync
    #collection_mode: hide
    #collection_order: release
    #url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/1960s.png
    #plex_search:
      #year.gte: 1960
      #year.lte: 1969

  1970s:
    sort_title: "!100_1970s"
    sync_mode: sync
    collection_mode: hide
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/1970s.png
    plex_search:
      year.gte: 1970
      year.lte: 1979

  1980s:
    sort_title: "!100_1980s"
    sync_mode: sync
    collection_mode: hide
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/1980s.png
    plex_search:
      year.gte: 1980
      year.lte: 1989

  1990s:
    sort_title: "!100_1990s"
    sync_mode: sync
    collection_mode: hide
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/1990s.png
    plex_search:
      year.gte: 1990
      year.lte: 1999

  2000s:
    sort_title: "!100_2000s"
    sync_mode: sync
    collection_mode: hide
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/2000s.png
    plex_search:
      year.gte: 2000
      year.lte: 2009

  2010s:
    sort_title: "!100_2010s"
    sync_mode: sync
    collection_mode: hide
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/2010s.png
    plex_search:
      year.gte: 2010
      year.lte: 2019

  2020s:
    sort_title: "!100_2020s"
    sync_mode: sync
    collection_mode: hide
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/2020s.png
    plex_search:
      year.gte: 2020
      year.lte: 2029

  #2030s:
    #sort_title: "!100_2030s"
    #sync_mode: sync
    #collection_mode: hide
    #collection_order: release
    #url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/decades/2030s.png
    #plex_search:
      #year.gte: 2030
      #year.lte: 2039

  ##################################################
  # Universes
  ##################################################

  ##################################################
  # In Association with Marvel
  ##################################################

  In Association with Marvel*:
    sort_title: "!040_In Association with Marvel"

    tmdb_movie:
      - 36647  # Blade (1998)
      - 36586  # Blade II (2002)
      - 36648  # Blade: Trinity (2004)

      - 9480   # Daredevil (2003)
      - 9947   # Elektra (2005)

      - 9738   # Fantastic Four (2005)
      - 1979   # Fantastic Four: Rise of the Silver Surfer (2007)
      - 166424 # Fantastic Four (2015)

      - 1250   # Ghost Rider (2007)
      - 71676  # Ghost Rider: Spirit of Vengeance (2011)

      - 10658  # Howard the Duck (1986)

      - 1927   # Hulk (2003)

      - 8867   # The Punisher (1989)
      - 7220   # The Punisher (2004)
      - 13056  # Punisher: War Zone (2008)

      - 557    # Spider-Man (2002)
      - 558    # Spider-Man 2 (2004)
      - 559    # Spider-Man 3 (2007)

      - 1930   # The Amazing Spider-Man (2012)
      - 102382 # The Amazing Spider-Man 2 (2014)

      - 324857 # Spider-Man: Into the Spider-Verse (2018)
      - 569094 # Spider-Man: Across the Spider-Verse (2023)

      - 335983 # Venom (2018)
      - 580489 # Venom: Let There Be Carnage (2021)
      - 526896 # Morbius (2022)
      - 634492 # Madame Web (2024)
      - 912649 # Venom: The Last Dance (2024)
      - 539972 # Kraven the Hunter (2024)

      - 36657  # X-Men (2000)
      - 36658  # X2: X-Men United (2003)
      - 36668  # X-Men: The Last Stand (2006)
      - 2080   # X-Men Origins: Wolverine (2009)
      - 49538  # X-Men: First Class (2011)
      - 76170  # The Wolverine (2013)
      - 127585 # X-Men: Days of Future Past (2014)
      - 293660 # Deadpool (2016)
      - 246655 # X-Men: Apocalypse (2016)
      - 263115 # Logan (2017)
      - 383498 # Deadpool 2 (2018)
      - 320288 # Dark Phoenix (2019)
      - 340102 # The New Mutants (2020)

      - 177572 # Big Hero 6 (2014)

    sync_mode: sync
    collection_mode: hide
    collection_order: custom

  ##################################################
  # Marvel Cinematic Universe
  ##################################################

  Marvel Cinematic Universe*:
    sort_title: "!040_Marvel Cinematic Universe*"
    imdb_list:
      list_id: ls539646485
    sync_mode: sync
    collection_mode: hide
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/mcu/mcu-release.jpg

  ##################################################
  # Middle Earth
  ##################################################

  Middle Earth*:
    sort_title: "!040_Middle Earth*"
    tmdb_movie:
      - 120       # The Lord of the Rings: The Fellowship of the Ring (2001)
      - 121       # The Lord of the Rings: The Two Towers (2002)
      - 122       # The Lord of the Rings: The Return of the King (2003)
      - 49051     # The Hobbit: An Unexpected Journey (2012)
      - 57158     # The Hobbit: The Desolation of Smaug (2013)
      - 122917    # The Hobbit: The Battle of the Five Armies (2014)
    sync_mode: sync
    collection_mode: hide
    collection_order: release
    
    url_poster: https://raw.githubusercontent.com/Kometa-Team/Default-Images/master/universe/middle.jpg
    # url_background: 

  ##################################################
  # View Askewniverse
  ##################################################

  View Askewniverse*:
    sort_title: "!040_View Askewniverse*"
    tmdb_movie:
      - 2292      # Clerks (1994)
      - 2293      # Mallrats (1995)
      - 2255      # Chasing Amy (1997)
      - 1832      # Dogma (1999)
      - 2294      # Jay and Silent Bob Strike Back (2001)
      - 2295      # Clerks II (2006)
      - 179267    # Jay & Silent Bob's Super Groovy Cartoon Movie! (2013)
      - 440762    # Jay and Silent Bob Reboot (2019)
      - 635891    # Clerks III (2022)
    sync_mode: sync
    collection_mode: hide
    collection_order: release

    url_poster: https://raw.githubusercontent.com/Kometa-Team/Default-Images/master/universe/askew.jpg
    # url_background:

  ##################################################
  # Wizarding World
  ##################################################

  Wizarding World*:
    sort_title: "!040_Wizarding World*"
    tmdb_movie:
      - 671       # Harry Potter and the Sorcerer's Stone (2001)
      - 672       # Harry Potter and the Chamber of Secrets (2002)
      - 673       # Harry Potter and the Prisoner of Azkaban (2004)
      - 674       # Harry Potter and the Goblet of Fire (2005)
      - 675       # Harry Potter and the Order of the Phoenix (2007)
      - 767       # Harry Potter and the Half-Blood Prince (2009)
      - 12444     # Harry Potter and the Deathly Hallows: Part 1 (2010)
      - 12445     # Harry Potter and the Deathly Hallows: Part 2 (2011)
      - 259316    # Fantastic Beasts and Where to Find Them (2016)
      - 338952    # Fantastic Beasts: The Crimes of Grindelwald (2018)
      - 338953    # Fantastic Beasts: The Secrets of Dumbledore (2022)
    sync_mode: sync
    collection_mode: hide
    collection_order: release

    url_poster: https://raw.githubusercontent.com/Kometa-Team/Default-Images/master/universe/wizard.jpg
    # url_background:
    
  ##################################################
  # X-Men Universe
  ##################################################

  X-Men Universe*:
    sort_title: "!040_X-Men Universe*"
    tmdb_movie:
      - 36657     # X-Men (2000)
      - 36658     # X2: X-Men United (2003)
      - 36668     # X-Men: The Last Stand (2006)
      - 2080      # X-Men Origins: Wolverine (2009)
      - 49538     # X-Men: First Class (2011)
      - 76170     # The Wolverine (2013)
      - 127585    # X-Men: Days of Future Past (2014)
      - 293660    # Deadpool (2016)
      - 246655    # X-Men: Apocalypse (2016)
      - 263115    # Logan (2017)
      - 383498    # Deadpool 2 (2018)
      - 320288    # Dark Phoenix (2019)
      - 340102    # The New Mutants (2020)
      - 533535    # Deadpool & Wolverine (2024)
    sync_mode: sync
    collection_mode: hide
    collection_order: release

    url_poster: https://raw.githubusercontent.com/Kometa-Team/Default-Images/master/universe/xmen.jpg
    # url_background:


  ##################################################
  # Franchises
  ##################################################

  ##################################################
  # Franchise Collections Separator
  ##################################################

  Franchise Collections:
    sort_title: "!050_Franchise Collections"
    blank_collection: true
    collection_mode: hide
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/separators/franchise-separator.png 
    
  ##################################################
  # Cornetto Trilogy
  ##################################################

  Cornetto Trilogy*:
    sort_title: "!050_Cornetto Trilogy"
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    tmdb_movie:
      - 747 # Shaun of the Dead (2004)
      - 4638 # Hot Fuzz (2007)
      - 107985 # The World's End (2013)
    url_poster: https://theposterdb.com/api/assets/284240
    
  ##################################################
  # Wolverine
  ##################################################

  Wolverine*:
    tmdb_movie:
      - 2080    # X-Men Origins: Wolverine (2009)
      - 76170   # The Wolverine (2013)
      - 263115  # Logan (2017)
    sync_mode: sync
    collection_mode: hide
    collection_order: release
    url_poster: https://api.mediux.pro/assets/3d1d4040-97c0-4260-941c-590e817418d6