collections:
    
  ##################################################
  # Movie Library
  ##################################################

  Movie Library:
    sort_title: "!999_!Movie Library"
    blank_collection: true
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/separators/movie-library.png    
    
 ##################################################
 # Art Label Reset — MAINTENANCE ONLY
 ##################################################

#  Art Label Reset:
#    build_collection: false
#    plex_all: true
#    item_label.remove: Art*

  ##################################################
  # Random Unwatched Movies
  ##################################################

  Random Unwatched Movies*:
    sort_title: "!015_Random Unwatched Movies"
    smart_filter:
      all:
        unplayed: true
      sort_by: random
    url_poster: https://raw.githubusercontent.com/...

 ##################################################
 # Decades
 ##################################################

  Decade Collections:
    sort_title: "!100_!Decade Collections"
    blank_collection: true
    url_poster: https://raw.githubusercontent.com/Kometa-Team/Default-Images/master/separators/orig/decade.jpg

  #1910s:
    #sort_title: "!100_1910s"
    #sync_mode: sync
    #collection_order: release
    #url_poster: https://theposterdb.com/api/assets/213578
    #plex_search:
      #year.gte: 1910
      #year.lte: 1919

  #1920s:
    #sort_title: "!100_1920s"
    #sync_mode: sync
    #collection_order: release
    #url_poster: https://theposterdb.com/api/assets/213579
    #plex_search:
      #year.gte: 1920
      #year.lte: 1929

  1930s:
    sort_title: "!100_1930s"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/213580
    plex_search:
      year.gte: 1930
      year.lte: 1939

  1940s:
    sort_title: "!100_1940s"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/213581
    plex_search:
      year.gte: 1940
      year.lte: 1949

  1950s:
    sort_title: "!100_1950s"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/213582
    plex_search:
      year.gte: 1950
      year.lte: 1959

  1960s:
    sort_title: "!100_1960s"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/213583
    plex_search:
      year.gte: 1960
      year.lte: 1969

  1970s:
    sort_title: "!100_1970s"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/213584
    plex_search:
      year.gte: 1970
      year.lte: 1979

  1980s:
    sort_title: "!100_1980s"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/213585
    plex_search:
      year.gte: 1980
      year.lte: 1989

  1990s:
    sort_title: "!100_1990s"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/213586
    plex_search:
      year.gte: 1990
      year.lte: 1999

  2000s:
    sort_title: "!100_2000s"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/213587
    plex_search:
      year.gte: 2000
      year.lte: 2009

  2010s:
    sort_title: "!100_2010s"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/213588
    plex_search:
      year.gte: 2010
      year.lte: 2019

  2020s:
    sort_title: "!100_2020s"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/213589
    plex_search:
      year.gte: 2020
      year.lte: 2029

  #2030s:
    #sort_title: "!100_2030s"
    #sync_mode: sync
    #collection_order: release
    #url_poster: https://theposterdb.com/api/assets/213590
    #plex_search:
      #year.gte: 2030
      #year.lte: 2039

 ##################################################
 # Universes
 ##################################################

  ##################################################
  # In Association with Marvel
  ##################################################

  In Association with Marvel*:
    sort_title: "!040_In Association with Marvel*"
    tmdb_movie:
      - 36647  # Blade (1998)
      - 36586  # Blade II (2002)
      - 36648  # Blade: Trinity (2004)
      - 9480   # Daredevil (2003)
      - 9947   # Elektra (2005)
      - 9738   # Fantastic Four (2005)
      - 1979   # Fantastic Four: Rise of the Silver Surfer (2007)
      - 166424 # Fantastic Four (2015)
      - 1250   # Ghost Rider (2007)
      - 71676  # Ghost Rider: Spirit of Vengeance (2011)
      - 10658  # Howard the Duck (1986)
      - 1927   # Hulk (2003)
      - 8867   # The Punisher (1989)
      - 7220   # The Punisher (2004)
      - 13056  # Punisher: War Zone (2008)
      - 557    # Spider-Man (2002)
      - 558    # Spider-Man 2 (2004)
      - 559    # Spider-Man 3 (2007)
      - 1930   # The Amazing Spider-Man (2012)
      - 102382 # The Amazing Spider-Man 2 (2014)
      - 324857 # Spider-Man: Into the Spider-Verse (2018)
      - 569094 # Spider-Man: Across the Spider-Verse (2023)
      - 335983 # Venom (2018)
      - 580489 # Venom: Let There Be Carnage (2021)
      - 526896 # Morbius (2022)
      - 634492 # Madame Web (2024)
      - 912649 # Venom: The Last Dance (2024)
      - 539972 # Kraven the Hunter (2024)
      - 36657  # X-Men (2000)
      - 36658  # X2: X-Men United (2003)
      - 36668  # X-Men: The Last Stand (2006)
      - 2080   # X-Men Origins: Wolverine (2009)
      - 49538  # X-Men: First Class (2011)
      - 76170  # The Wolverine (2013)
      - 127585 # X-Men: Days of Future Past (2014)
      - 293660 # Deadpool (2016)
      - 246655 # X-Men: Apocalypse (2016)
      - 263115 # Logan (2017)
      - 383498 # Deadpool 2 (2018)
      - 320288 # Dark Phoenix (2019)
      - 340102 # The New Mutants (2020)
      - 177572 # Big Hero 6 (2014)
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/125372

  ##################################################
  # Middle Earth
  ##################################################

  Middle Earth*:
    sort_title: "!040_Middle Earth*"
    tmdb_movie:
      - 120       # The Lord of the Rings: The Fellowship of the Ring (2001)
      - 121       # The Lord of the Rings: The Two Towers (2002)
      - 122       # The Lord of the Rings: The Return of the King (2003)
      - 49051     # The Hobbit: An Unexpected Journey (2012)
      - 57158     # The Hobbit: The Desolation of Smaug (2013)
      - 122917    # The Hobbit: The Battle of the Five Armies (2014)
    sync_mode: sync
    collection_order: release
    
    url_poster: https://theposterdb.com/api/assets/264226
    # url_background: 

  ##################################################
  # View Askewniverse
  ##################################################

  View Askewniverse*:
    sort_title: "!040_View Askewniverse*"
    tmdb_movie:
      - 2292      # Clerks (1994)
      - 2293      # Mallrats (1995)
      - 2255      # Chasing Amy (1997)
      - 1832      # Dogma (1999)
      - 2294      # Jay and Silent Bob Strike Back (2001)
      - 2295      # Clerks II (2006)
      - 179267    # Jay & Silent Bob's Super Groovy Cartoon Movie! (2013)
      - 440762    # Jay and Silent Bob Reboot (2019)
      - 635891    # Clerks III (2022)
    sync_mode: sync
    collection_order: release

    url_poster: https://theposterdb.com/api/assets/171375
    # url_background:

  ##################################################
  # Wizarding World
  ##################################################

  Wizarding World*:
    sort_title: "!040_Wizarding World*"
    tmdb_movie:
      - 671       # Harry Potter and the Sorcerer's Stone (2001)
      - 672       # Harry Potter and the Chamber of Secrets (2002)
      - 673       # Harry Potter and the Prisoner of Azkaban (2004)
      - 674       # Harry Potter and the Goblet of Fire (2005)
      - 675       # Harry Potter and the Order of the Phoenix (2007)
      - 767       # Harry Potter and the Half-Blood Prince (2009)
      - 12444     # Harry Potter and the Deathly Hallows: Part 1 (2010)
      - 12445     # Harry Potter and the Deathly Hallows: Part 2 (2011)
      - 259316    # Fantastic Beasts and Where to Find Them (2016)
      - 338952    # Fantastic Beasts: The Crimes of Grindelwald (2018)
      - 338953    # Fantastic Beasts: The Secrets of Dumbledore (2022)
    sync_mode: sync
    collection_order: release

    url_poster: https://theposterdb.com/api/assets/1269
    # url_background:
    
  ##################################################
  # X-Men Universe
  ##################################################

  X-Men Universe*:
    sort_title: "!040_X-Men Universe*"
    sync_mode: sync
    collection_order: release
    url_poster: https://theposterdb.com/api/assets/143883
    tmdb_movie:
      - 36657     # X-Men (2000)
      - 36658     # X2: X-Men United (2003)
      - 36668     # X-Men: The Last Stand (2006)
      - 2080      # X-Men Origins: Wolverine (2009)
      - 49538     # X-Men: First Class (2011)
      - 76170     # The Wolverine (2013)
      - 127585    # X-Men: Days of Future Past (2014)
      - 293660    # Deadpool (2016)
      - 246655    # X-Men: Apocalypse (2016)
      - 263115    # Logan (2017)
      - 383498    # Deadpool 2 (2018)
      - 320288    # Dark Phoenix (2019)
      - 340102    # The New Mutants (2020)
      - 533535    # Deadpool & Wolverine (2024)

 ##################################################
 # Studios
 ##################################################
 
 

  Studio Collections:
    sort_title: "!070_!Studio Collections"
    blank_collection: true
    url_poster: https://raw.githubusercontent.com/Kometa-Team/Default-Images/master/separators/orig/studio.jpg

  ##################################################
  # Pixar
  ##################################################

  Pixar*:
    sort_title: "!070_Pixar"
    collection_order: release.desc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/532233
    imdb_list:
      list_id: ls525761865
     
  ##################################################
  # Illumination Entertainment
  ##################################################

  Illumination Entertainment*:
    sort_title: "!070_Illumination Entertainment"
    collection_order: release.desc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/531342
    imdb_list:
      list_id: ls4117914193

  ##################################################
  # Disney Animation Studios
  ##################################################

  Disney Animation*:
    sort_title: "!070_Disney Animation Studios"
    collection_order: release.desc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/532946
    imdb_list:
      list_id: ls051452524

  ##################################################
  # Disney Live Action
  ##################################################

  Disney Live Action*:
    sort_title: "!070_Disney Live Action"
    collection_order: release.desc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/536979
    imdb_list:
      list_id: ls549040566

  ##################################################
  # DreamWorks Animation
  ##################################################

  DreamWorks Animation*:
    sort_title: "!070_DreamWorks Animation"
    collection_order: release.desc
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/531052
    imdb_list:
      list_id: ls4117290871

 ##################################################
 # Special Collections
 ##################################################

  Special Collections:
    sort_title: "!115_!Special Collections"
    blank_collection: true
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/special-collections.png

  ##################################################
  # Cornetto Trilogy
  ##################################################

  Cornetto Trilogy*:
    sort_title: "!115_Cornetto Trilogy"
    collection_order: release
    sync_mode: sync
    tmdb_movie:
      - 747 # Shaun of the Dead (2004)
      - 4638 # Hot Fuzz (2007)
      - 107985 # The World's End (2013)
    url_poster: https://theposterdb.com/api/assets/284240
    
  ##################################################
  # Broken Lizard
  ##################################################

  Broken Lizard*:
    sort_title: "!115_Broken Lizard"
    collection_order: release
    sync_mode: sync
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/custom/broken-lizard.png
    tmdb_movie:
      - 13563  # Puddle Cruiser (1996)
      - 39939  # Super Troopers (2001)
      - 11217  # Club Dread (2004)
      - 9988   # Beerfest (2006)
      - 34423  # The Slammin' Salmon (2009)
      - 50022  # Super Troopers 2 (2018)
      - 893752 # Quasi (2023)
      - 675871 # Super Troopers 3 (2026)
      
  ##################################################
  # Stand Up Comedy
  ##################################################

  Stand Up Comedy*:
    sort_title: "!016_Stand Up Comedy"
    plex_search:
      all:
        label: Stand Up
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/213081
    collection_order: release.desc

  Gabriel Iglesias*:
    sort_title: "Gabriel Iglesias 00"
    plex_search:
      all:
        label: Gabriel Iglesias
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/385080
    collection_order: release

  Jo Koy*:
    sort_title: "Jo Koy 00"
    plex_search:
      all:
        label: Jo Koy
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/307148
    collection_order: release

  Kevin Hart*:
    sort_title: "Kevin Hart 00"
    plex_search:
      all:
        label: Kevin Hart
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/259467
    collection_order: release
    
  Dave Chappelle*:
    sort_title: "Dave Chappelle 00"
    plex_search:
      all:
        label: Dave Chappelle
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/391639
    collection_order: release