libraries:

  ANIME:
    collection_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/anime/anime-collections.yml

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/anime/anime-metadata.yml
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/anime/cowboy-bebop-fix.yml

  ANIME MOVIES:
    collection_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/anime/anime-movie-collections.yml

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/anime/anime-movies-metadata.yml

  MATT MOVIES:
    collection_files:
    - default: franchise
      template_variables:
        collection_mode: show_items

        movie_9735:
        - 6466      # Freddy vs. Jason
        - 13207     # Friday the 13th (2009)

        movie_10:
        - 12180     # Star Wars: The Clone Wars
        - 330459     # Rogue One: A Star Wars Story
        - 348350     # Solo: A Star Wars Story
        - 1228710     # The Mandalorian and Grogu)

        exclude:
        - 135416     # Prometheus
        - 1149208     # Commando

        append_addons:
          8091:
          - 135416     # Prometheus -> Alien

        remove_addons:
          91361:
          - 126209     # Halloween (Rob Zombie Series)
          748:
          - 453993     # The Wolverine

        title_override:
          10: 'Star Wars: Skywalker Saga'
          535313: Godzilla (MonsterVerse)
          535790: Godzilla (Anime)
          507458: ThanksKilling
          
        sort_title_115762: Alien vs. Predator 00
        sort_title_10: Star Wars 00
        
        url_poster_125574: https://theposterdb.com/api/assets/132632   # The Amazing Spider-Man
        url_poster_8091: https://theposterdb.com/api/assets/2876   # Alien
        url_poster_402074: https://theposterdb.com/api/assets/13880   # Annabelle
        url_poster_93791: https://theposterdb.com/api/assets/11053   # Anchorman
        url_poster_422834: https://theposterdb.com/api/assets/295036   # Ant-Man
        url_poster_573693: https://theposterdb.com/api/assets/349724   # Aquaman
        url_poster_1006: https://theposterdb.com/api/assets/2883   # Austin Powers
        url_poster_87096: https://theposterdb.com/api/assets/348246   # Avatar
        url_poster_86311: https://theposterdb.com/api/assets/114054   # Avengers
        url_poster_115762: https://theposterdb.com/api/assets/13908   # AVP
        url_poster_264: https://theposterdb.com/api/assets/14631   # Back to the Future
        url_poster_14890: https://theposterdb.com/api/assets/2887   # Bad Boys
        url_poster_945475: https://theposterdb.com/api/assets/536944   # Beetlejuice
        url_poster_91746: https://theposterdb.com/api/assets/2891   # Bill & Ted
        url_poster_529892: https://theposterdb.com/api/assets/282450   # Black Panther
        url_poster_735: https://theposterdb.com/api/assets/139554   # Blade
        url_poster_747168: https://theposterdb.com/api/assets/133008   # Borat
        url_poster_131295: https://theposterdb.com/api/assets/114048   # Captain America
        url_poster_623911: https://theposterdb.com/api/assets/114049   # Captain Marvel
        url_poster_10455: https://theposterdb.com/api/assets/2903   # Chucky
        url_poster_182813: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/clerks-collection.png   # Clerks
        url_poster_313086: https://theposterdb.com/api/assets/2906   # The Conjuring
        url_poster_553717: https://theposterdb.com/api/assets/2908   # Creed
        url_poster_64751: https://theposterdb.com/api/assets/2907   # Crank
        url_poster_178106: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/darko-collection.png   # Darko
        url_poster_263: https://theposterdb.com/api/assets/141711   # The Dark Knight
        url_poster_448150: https://theposterdb.com/api/assets/135778   # Deadpool
        url_poster_95664: https://theposterdb.com/api/assets/68721   # Deuce Bigalow
        url_poster_1570: https://theposterdb.com/api/assets/2919   # Die Hard
        url_poster_618529: https://theposterdb.com/api/assets/114050   # Doctor Strange
        url_poster_96665: https://theposterdb.com/api/assets/144837   # Dumb and Dumber
        url_poster_435259: https://theposterdb.com/api/assets/2928   # Fantastic Beasts
        url_poster_9744: https://theposterdb.com/api/assets/151994   # Fantastic Four
        url_poster_9485: https://theposterdb.com/api/assets/6421   # Fast & Furious
        url_poster_9735: https://theposterdb.com/api/assets/2945   # Friday the 13th
        url_poster_90306: https://theposterdb.com/api/assets/152105   # Ghost Rider
        url_poster_284433: https://theposterdb.com/api/assets/291146   # Guardians of the Galaxy
        url_poster_91361: https://theposterdb.com/api/assets/2957   # Halloween
        url_poster_126209: https://theposterdb.com/api/assets/2956   # Halloween (Rob Zombie)
        url_poster_1241: https://theposterdb.com/api/assets/2960   # Harry Potter
        url_poster_121938: https://theposterdb.com/api/assets/2964   # The Hobbit
        url_poster_131292: https://theposterdb.com/api/assets/114052   # Iron Man
        url_poster_726870: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/jay-and-silent-bob.png   # Jay and Silent Bob
        url_poster_645: https://theposterdb.com/api/assets/2864   # James Bond
        url_poster_119: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/lotr.png   # The Lord of the Rings
        url_poster_209131: https://theposterdb.com/api/assets/131540   # Man of Steel
        url_poster_8581: https://theposterdb.com/api/assets/3027   # A Nightmare on Elm Street
        url_poster_968052: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/thenun.png   # The Nun
        url_poster_295: https://theposterdb.com/api/assets/3034   # Pirates of the Caribbean
        url_poster_399: https://theposterdb.com/api/assets/3050   # Predator
        url_poster_635362: https://theposterdb.com/api/assets/151892   # The Punisher
        url_poster_1575: https://theposterdb.com/api/assets/3071   # Rocky
        url_poster_4246: https://theposterdb.com/api/assets/3075   # Scary Movie
        url_poster_2602: https://theposterdb.com/api/assets/3077   # Scream
        url_poster_724848: https://theposterdb.com/api/assets/313308   # Shazam!
        url_poster_531241: https://theposterdb.com/api/assets/287939   # Spider-Man (Avengers)
        url_poster_556: https://theposterdb.com/api/assets/132628   # Spider-Man (Trilogy)
        url_poster_573436: https://theposterdb.com/api/assets/132635   # Spider-Verse
        url_poster_10: https://theposterdb.com/api/assets/13223   # Star Wars
        url_poster_531242: https://theposterdb.com/api/assets/139024   # Suicide Squad
        url_poster_507458: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/thankskilling.png   # ThanksKilling
        url_poster_131296: https://theposterdb.com/api/assets/249712   # Thor
        url_poster_558216: https://theposterdb.com/api/assets/153723   # Venom
        url_poster_453993: https://theposterdb.com/api/assets/152048   # The Wolverine
        url_poster_468552: https://theposterdb.com/api/assets/128646   # Wonder Woman
        url_poster_748: https://theposterdb.com/api/assets/143883   # X-Men 
        url_poster_86119: https://theposterdb.com/api/assets/6975   # The Hangover   
        
    - default: universe
      template_variables:
        collection_mode: show_items
        collection_order_star: release
        collection_order_avp: release
        collection_order_mcu: release
        url_poster_mcu: https://theposterdb.com/api/assets/143466   #MCU
        url_poster_dcu: https://theposterdb.com/api/assets/128645   # DC Universe
          #url_poster_wizard: https://theposterdb.com/api/assets/1269 # Wizarding World
          #url_poster_askew: https://theposterdb.com/api/assets/171375 # View Askewniverse
          #url_poster_middle: https://theposterdb.com/api/assets/264226 # Middle Earth
        url_poster_star: https://theposterdb.com/api/assets/133720   # Star Wars
        url_poster_conjuring: https://api.mediux.pro/assets/2f19f71f-b856-4f41-82d8-02ddb7ab6353   # Conjuring Universe
        url_poster_avp: https://theposterdb.com/api/assets/576790   # Alien / Predator Universe
        exclude:
        - fast
        - xmen

    - default: streaming
      template_variables:
        collection_mode: show_items
        minimum_items: 10


    #My Collection Overides
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie/movie-collections.yml
      template_variables:
        collection_mode: show_items

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie/movie-metadata.yml

    operations:
      delete_collections:
        configured: false
        managed: true

    #overlay_files:
    #- default: resolution

  MATT TV:
    operations:
      delete_collections:
        configured: false
        managed: true

    collection_files:
    - default: streaming
      template_variables:
        collection_mode: hide

    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv/tv-collections.yml

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv/tv-metadata.yml

  MATT MOVIES - 1080p:
    collection_files:
    - default: franchise
      template_variables:
        collection_mode: hide

        movie_9735:
        - 6466      # Freddy vs. Jason
        - 13207     # Friday the 13th (2009)

        movie_10:
        - 12180     # Star Wars: The Clone Wars
        - 330459     # Rogue One: A Star Wars Story
        - 348350     # Solo: A Star Wars Story
        - 1228710     # The Mandalorian and Grogu)

        exclude:
        - 135416     # Prometheus
        - 1149208     # Commando

        append_addons:
          8091:
          - 135416     # Prometheus -> Alien

        remove_addons:
          91361:
          - 126209     # Halloween (Rob Zombie Series)
          748:
          - 453993     # The Wolverine

        title_override:
          10: 'Star Wars: Skywalker Saga'
          535313: Godzilla (MonsterVerse)
          535790: Godzilla (Anime)
          507458: ThanksKilling
          
        sort_title_115762: Alien vs. Predator 00
        sort_title_10: Star Wars 00
        
        url_poster_125574: https://theposterdb.com/api/assets/132632   # The Amazing Spider-Man
        url_poster_8091: https://theposterdb.com/api/assets/2876   # Alien
        url_poster_402074: https://theposterdb.com/api/assets/13880   # Annabelle
        url_poster_93791: https://theposterdb.com/api/assets/11053   # Anchorman
        url_poster_422834: https://theposterdb.com/api/assets/295036   # Ant-Man
        url_poster_573693: https://theposterdb.com/api/assets/349724   # Aquaman
        url_poster_1006: https://theposterdb.com/api/assets/2883   # Austin Powers
        url_poster_87096: https://theposterdb.com/api/assets/348246   # Avatar
        url_poster_86311: https://theposterdb.com/api/assets/114054   # Avengers
        url_poster_115762: https://theposterdb.com/api/assets/13908   # AVP
        url_poster_264: https://theposterdb.com/api/assets/14631   # Back to the Future
        url_poster_14890: https://theposterdb.com/api/assets/2887   # Bad Boys
        url_poster_945475: https://theposterdb.com/api/assets/536944   # Beetlejuice
        url_poster_91746: https://theposterdb.com/api/assets/2891   # Bill & Ted
        url_poster_529892: https://theposterdb.com/api/assets/282450   # Black Panther
        url_poster_735: https://theposterdb.com/api/assets/139554   # Blade
        url_poster_747168: https://theposterdb.com/api/assets/133008   # Borat
        url_poster_131295: https://theposterdb.com/api/assets/114048   # Captain America
        url_poster_623911: https://theposterdb.com/api/assets/114049   # Captain Marvel
        url_poster_10455: https://theposterdb.com/api/assets/2903   # Chucky
        url_poster_182813: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/clerks-collection.png   # Clerks
        url_poster_313086: https://theposterdb.com/api/assets/2906   # The Conjuring
        url_poster_553717: https://theposterdb.com/api/assets/2908   # Creed
        url_poster_64751: https://theposterdb.com/api/assets/2907   # Crank
        url_poster_178106: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/darko-collection.png   # Darko
        url_poster_263: https://theposterdb.com/api/assets/141711   # The Dark Knight
        url_poster_448150: https://theposterdb.com/api/assets/135778   # Deadpool
        url_poster_95664: https://theposterdb.com/api/assets/68721   # Deuce Bigalow
        url_poster_1570: https://theposterdb.com/api/assets/2919   # Die Hard
        url_poster_618529: https://theposterdb.com/api/assets/114050   # Doctor Strange
        url_poster_96665: https://theposterdb.com/api/assets/144837   # Dumb and Dumber
        url_poster_435259: https://theposterdb.com/api/assets/2928   # Fantastic Beasts
        url_poster_9744: https://theposterdb.com/api/assets/151994   # Fantastic Four
        url_poster_9485: https://theposterdb.com/api/assets/6421   # Fast & Furious
        url_poster_9735: https://theposterdb.com/api/assets/2945   # Friday the 13th
        url_poster_90306: https://theposterdb.com/api/assets/152105   # Ghost Rider
        url_poster_284433: https://theposterdb.com/api/assets/291146   # Guardians of the Galaxy
        url_poster_91361: https://theposterdb.com/api/assets/2957   # Halloween
        url_poster_126209: https://theposterdb.com/api/assets/2956   # Halloween (Rob Zombie)
        url_poster_1241: https://theposterdb.com/api/assets/2960   # Harry Potter
        url_poster_121938: https://theposterdb.com/api/assets/2964   # The Hobbit
        url_poster_131292: https://theposterdb.com/api/assets/114052   # Iron Man
        url_poster_726870: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/jay-and-silent-bob.png   # Jay and Silent Bob
        url_poster_645: https://theposterdb.com/api/assets/2864   # James Bond
        url_poster_119: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/lotr.png   # The Lord of the Rings
        url_poster_209131: https://theposterdb.com/api/assets/131540   # Man of Steel
        url_poster_8581: https://theposterdb.com/api/assets/3027   # A Nightmare on Elm Street
        url_poster_968052: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/thenun.png   # The Nun
        url_poster_295: https://theposterdb.com/api/assets/3034   # Pirates of the Caribbean
        url_poster_399: https://theposterdb.com/api/assets/3050   # Predator
        url_poster_635362: https://theposterdb.com/api/assets/151892   # The Punisher
        url_poster_1575: https://theposterdb.com/api/assets/3071   # Rocky
        url_poster_4246: https://theposterdb.com/api/assets/3075   # Scary Movie
        url_poster_2602: https://theposterdb.com/api/assets/3077   # Scream
        url_poster_724848: https://theposterdb.com/api/assets/313308   # Shazam!
        url_poster_531241: https://theposterdb.com/api/assets/287939   # Spider-Man (Avengers)
        url_poster_556: https://theposterdb.com/api/assets/132628   # Spider-Man (Trilogy)
        url_poster_573436: https://theposterdb.com/api/assets/132635   # Spider-Verse
        url_poster_10: https://theposterdb.com/api/assets/13223   # Star Wars
        url_poster_531242: https://theposterdb.com/api/assets/139024   # Suicide Squad
        url_poster_507458: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/thankskilling.png   # ThanksKilling
        url_poster_131296: https://theposterdb.com/api/assets/249712   # Thor
        url_poster_558216: https://theposterdb.com/api/assets/153723   # Venom
        url_poster_453993: https://theposterdb.com/api/assets/152048   # The Wolverine
        url_poster_468552: https://theposterdb.com/api/assets/128646   # Wonder Woman
        url_poster_748: https://theposterdb.com/api/assets/143883   # X-Men 
        url_poster_86119: https://theposterdb.com/api/assets/6975   # The Hangover   
        
    - default: universe
      template_variables:
        collection_mode: hide
        collection_order_star: release
        collection_order_avp: release
        collection_order_mcu: release
        url_poster_mcu: https://theposterdb.com/api/assets/143466   #MCU
        url_poster_dcu: https://theposterdb.com/api/assets/128645   # DC Universe
          #url_poster_wizard: https://theposterdb.com/api/assets/1269 # Wizarding World
          #url_poster_askew: https://theposterdb.com/api/assets/171375 # View Askewniverse
          #url_poster_middle: https://theposterdb.com/api/assets/264226 # Middle Earth
        url_poster_star: https://theposterdb.com/api/assets/133720   # Star Wars
        url_poster_conjuring: https://api.mediux.pro/assets/2f19f71f-b856-4f41-82d8-02ddb7ab6353   # Conjuring Universe
        url_poster_avp: https://theposterdb.com/api/assets/576790   # Alien / Predator Universe
        exclude:
        - fast
        - xmen

    - default: streaming
      template_variables:
        collection_mode: hide
        minimum_items: 10

    #My Collection Overides
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie/movie-collections.yml
      template_variables:
        collection_mode: hide

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie/movie-metadata.yml

    operations:
      delete_collections:
        configured: false
        managed: true

    #overlay_files:
    #- default: resolution

  MATT TV - 1080p:
    operations:
      delete_collections:
        configured: false
        managed: true

    collection_files:
    - default: streaming
      template_variables:
        collection_mode: hide

    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv/tv-collections.yml

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv/tv-metadata.yml

  WWE Events:
    overlay_files:
    - default: resolution

  #Stand Up Comedy:
    #overlay_files:
    #- default: resolution