libraries:

  MATT MOVIES:
    operations:
      delete_collections:
        configured: false
        managed: true

    collection_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie-collections.yml
    
    - default: franchise
      template_variables:
        collection_mode: hide
        url_poster_422834: https://api.mediux.pro/assets/6e438cab-bba2-4431-b49d-f86b6cad2bc1 # Ant-Man
        url_poster_86311: https://api.mediux.pro/assets/5128b262-d055-4b0f-a1ba-28280e35a022 # Avengers
        url_poster_529892: https://api.mediux.pro/assets/8b18bc52-9df1-4388-aedb-731d7b23aced # Black Panther
        url_poster_131295: https://api.mediux.pro/assets/c3860668-c1ed-41fa-9fa3-711a3fb6755d # Captain America
        url_poster_623911: https://api.mediux.pro/assets/77df6f32-e2aa-4cdf-9eed-ee10ec5f79d7 # Captain Marvel
        url_poster_182813: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/view_askewniverse/clerks-poster.jpg # Clerks
        url_poster_448150: https://api.mediux.pro/assets/4f6abbaf-8b26-436c-9501-82638ea4f287 # Deadpool
        url_poster_618529: https://api.mediux.pro/assets/7554a132-391b-4df7-a389-0f7d7345ecda # Doctor Strange
        url_poster_435259: https://api.mediux.pro/assets/332dd54d-97ce-4ee2-818a-664182c65d78 # Fantastic Beasts
        url_poster_9485: https://api.mediux.pro/assets/26a25f6f-b296-4380-8d72-ebaaa1b42982 # Fast & Furious
        url_poster_284433: https://api.mediux.pro/assets/1d8e24ea-7029-43a8-895b-84be90a30769 # Guardians of the Galaxy
        url_poster_1241: https://api.mediux.pro/assets/fddb4374-62fa-4e29-b0bc-364215ef4280 # Harry Potter
        url_poster_131292: https://api.mediux.pro/assets/276ee4a9-875b-4324-a612-2a214a2e5d31 # Iron Man
        url_poster_726870: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/view_askewniverse/jay-and-silent-bob-poster.jpg # Jay and Silent Bob
        url_poster_119: https://api.mediux.pro/assets/0e957d39-59c6-4419-871b-fb250dc5ed77 # The Lord of the Rings
        url_poster_295: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/potc/pirates-of-the-caribbean-collection.png # Pirates of the Caribbean
        url_poster_531241: https://api.mediux.pro/assets/c3d5982f-1baa-4959-b764-361f40342d8e # Spider-Man (Avengers)
        url_poster_10: https://api.mediux.pro/assets/60209ad6-d0a8-4d55-a42a-ec0e9e1de3ae # Star Wars: Skywalker Saga
        url_poster_121938: https://api.mediux.pro/assets/b8a558a5-b6fe-423b-92e9-649c25eaa5e7 # The Hobbit
        url_poster_131296: https://api.mediux.pro/assets/639ade15-6556-4a6b-ae24-84350574415a # Thor
        url_poster_748: https://api.mediux.pro/assets/f69cb745-5117-49f4-bfc5-f8f84cd8aa35 # X-Men
        
    - default: universe
      template_variables:
        collection_mode: hide
        collection_order_star: release
        url_poster_mcu: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/mcu/mcu-timeline.jpg
        exclude:
          - fast
          - xmen
          
    #- url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie-collectionless.yml

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie-metadata.yml

    #overlay_files:
    #- default: resolution

  MATT TV:
    operations:
      delete_collections:
        configured: false
        managed: true

    collection_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv-collections.yml

    - default: network
      template_variables:
        collection_mode: hide

    - default: streaming
      template_variables:
        collection_mode: hide

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv-metadata.yml

  MATT MOVIES - 1080p:
    operations:
      delete_collections:
        configured: false
        managed: true

    collection_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie-collections.yml
    
    - default: franchise
      template_variables:
        collection_mode: hide
        url_poster_422834: https://api.mediux.pro/assets/6e438cab-bba2-4431-b49d-f86b6cad2bc1 # Ant-Man
        url_poster_86311: https://api.mediux.pro/assets/5128b262-d055-4b0f-a1ba-28280e35a022 # Avengers
        url_poster_529892: https://api.mediux.pro/assets/8b18bc52-9df1-4388-aedb-731d7b23aced # Black Panther
        url_poster_131295: https://api.mediux.pro/assets/c3860668-c1ed-41fa-9fa3-711a3fb6755d # Captain America
        url_poster_623911: https://api.mediux.pro/assets/77df6f32-e2aa-4cdf-9eed-ee10ec5f79d7 # Captain Marvel
        url_poster_182813: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/view_askewniverse/clerks-poster.jpg # Clerks
        url_poster_448150: https://api.mediux.pro/assets/4f6abbaf-8b26-436c-9501-82638ea4f287 # Deadpool
        url_poster_618529: https://api.mediux.pro/assets/7554a132-391b-4df7-a389-0f7d7345ecda # Doctor Strange
        url_poster_435259: https://api.mediux.pro/assets/332dd54d-97ce-4ee2-818a-664182c65d78 # Fantastic Beasts
        url_poster_9485: https://api.mediux.pro/assets/26a25f6f-b296-4380-8d72-ebaaa1b42982 # Fast & Furious
        url_poster_284433: https://api.mediux.pro/assets/1d8e24ea-7029-43a8-895b-84be90a30769 # Guardians of the Galaxy
        url_poster_1241: https://api.mediux.pro/assets/fddb4374-62fa-4e29-b0bc-364215ef4280 # Harry Potter
        url_poster_131292: https://api.mediux.pro/assets/276ee4a9-875b-4324-a612-2a214a2e5d31 # Iron Man
        url_poster_726870: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/view_askewniverse/jay-and-silent-bob-poster.jpg # Jay and Silent Bob
        url_poster_119: https://api.mediux.pro/assets/0e957d39-59c6-4419-871b-fb250dc5ed77 # The Lord of the Rings
        url_poster_295: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/potc/pirates-of-the-caribbean-collection.png # Pirates of the Caribbean
        url_poster_531241: https://api.mediux.pro/assets/c3d5982f-1baa-4959-b764-361f40342d8e # Spider-Man (Avengers)
        url_poster_10: https://api.mediux.pro/assets/60209ad6-d0a8-4d55-a42a-ec0e9e1de3ae # Star Wars: Skywalker Saga
        url_poster_121938: https://api.mediux.pro/assets/b8a558a5-b6fe-423b-92e9-649c25eaa5e7 # The Hobbit
        url_poster_131296: https://api.mediux.pro/assets/639ade15-6556-4a6b-ae24-84350574415a # Thor
        url_poster_748: https://api.mediux.pro/assets/f69cb745-5117-49f4-bfc5-f8f84cd8aa35 # X-Men
        
    - default: universe
      template_variables:
        collection_mode: hide
        collection_order_star: release
        url_poster_mcu: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/mcu/mcu-timeline.jpg
        exclude:
          - fast
          - xmen
          
    #- url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie-collectionless.yml

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie-metadata.yml

    #overlay_files:
    #- default: resolution

  MATT TV - 1080p:
    operations:
      delete_collections:
        configured: false
        managed: true

    collection_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv-collections.yml

    - default: network
      template_variables:
        collection_mode: hide

    - default: streaming
      template_variables:
        collection_mode: hide

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv-metadata.yml

  WWE Events:
    overlay_files:
    - default: resolution

  #Stand Up Comedy:
    #overlay_files:
    #- default: resolution