libraries:

  MATT TV:
    operations:
      delete_collections:
        configured: false
        managed: true

    collection_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv-collections.yml

    - default: network
    - default: streaming

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv-metadata.yml

  MATT MOVIES:
    operations:
      delete_collections:
        configured: false
        managed: true

    collection_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie-collections.yml
    
    - default: franchise
      template_variables:
        collection_mode: hide
        url_poster_422834: https://api.mediux.pro/assets/6e438cab-bba2-4431-b49d-f86b6cad2bc1 # Ant-Man
        url_poster_182813: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/view_askewniverse/clerks-poster.jpg # Clerks
        url_poster_435259: https://api.mediux.pro/assets/332dd54d-97ce-4ee2-818a-664182c65d78 # Fantastic Beasts
        url_poster_1241: https://api.mediux.pro/assets/fddb4374-62fa-4e29-b0bc-364215ef4280 # Harry Potter
        url_poster_726871: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/view_askewniverse/jay-and-silent-bob-poster.jpg # Jay and Silent Bob
        
    - default: universe
      template_variables:
        exclude:
          - xmen

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie-metadata.yml

    #overlay_files:
    #- default: resolution

  MATT MOVIES - 1080p:
    operations:
      delete_collections:
        configured: false
        managed: true

    collection_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie-collections.yml
    
    - default: franchise
      template_variables:
        url_poster_422834: https://api.mediux.pro/assets/6e438cab-bba2-4431-b49d-f86b6cad2bc1 # Ant-Man
        url_poster_182813: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/view_askewniverse/clerks-poster.jpg # Clerks
        url_poster_435259: https://api.mediux.pro/assets/332dd54d-97ce-4ee2-818a-664182c65d78 # Fantastic Beasts
        url_poster_1241: https://api.mediux.pro/assets/fddb4374-62fa-4e29-b0bc-364215ef4280 # Harry Potter
        url_poster_726871: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/view_askewniverse/jay-and-silent-bob-poster.jpg # Jay and Silent Bob
        
    - default: universe
      template_variables:
        exclude:
          - xmen

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/movie-metadata.yml

    #overlay_files:
    #- default: resolution

  MATT TV - 1080p:
    operations:
      delete_collections:
        configured: false
        managed: true

    collection_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv-collections.yml

    - default: network
    - default: streaming

    metadata_files:
    - url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/config/tv-metadata.yml

  WWE Events:
    overlay_files:
    - default: resolution

  #Stand Up Comedy:
    #overlay_files:
    #- default: resolution