collections:

  ##################################################
  # Decades
  ##################################################

  1910s:
    sort_title: "!01 - 1910s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/1910s.png
    plex_search:
      year.gte: 1910
      year.lte: 1919

  1920s:
    sort_title: "!02 - 1920s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/1920s.png
    plex_search:
      year.gte: 1920
      year.lte: 1929

  1930s:
    sort_title: "!03 - 1930s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/1930s.png
    plex_search:
      year.gte: 1930
      year.lte: 1939

  1940s:
    sort_title: "!04 - 1940s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/1940s.png
    plex_search:
      year.gte: 1940
      year.lte: 1949

  1950s:
    sort_title: "!05 - 1950s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/1950s.png
    plex_search:
      year.gte: 1950
      year.lte: 1959

  1960s:
    sort_title: "!06 - 1960s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/1960s.png
    plex_search:
      year.gte: 1960
      year.lte: 1969

  1970s:
    sort_title: "!07 - 1970s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/1970s.png
    plex_search:
      year.gte: 1970
      year.lte: 1979

  1980s:
    sort_title: "!08 - 1980s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/1980s.png
    plex_search:
      year.gte: 1980
      year.lte: 1989

  1990s:
    sort_title: "!09 - 1990s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/1990s.png
    plex_search:
      year.gte: 1990
      year.lte: 1999

  2000s:
    sort_title: "!10 - 2000s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/2000s.png
    plex_search:
      year.gte: 2000
      year.lte: 2009

  2010s:
    sort_title: "!11 - 2010s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/2010s.png
    plex_search:
      year.gte: 2010
      year.lte: 2019

  2020s:
    sort_title: "!12 - 2020s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/2020s.png
    plex_search:
      year.gte: 2020
      year.lte: 2029

  2030s:
    sort_title: "!13 - 2030s"
    sync_mode: sync
    collection_order: release
    url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/decades/2030s.png
    plex_search:
      year.gte: 2030
      year.lte: 2039

  ##################################################
  # Universes
  ##################################################

  #Marvel Cinematic Universe*:
    #sort_title: "!040_Marvel Cinematic Universe*"
    #imdb_list:
      #list_id: ls539646485
    #sync_mode: sync
    #collection_mode: show_items
    #collection_order: release
    
    #url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/mcu/mcu-poster.jpg
    # url_background:

  Middle Earth*:
    sort_title: "!040_Middle Earth*"
    tmdb_movie:
      - 120       # The Lord of the Rings: The Fellowship of the Ring (2001)
      - 121       # The Lord of the Rings: The Two Towers (2002)
      - 122       # The Lord of the Rings: The Return of the King (2003)
      - 49051     # The Hobbit: An Unexpected Journey (2012)
      - 57158     # The Hobbit: The Desolation of Smaug (2013)
      - 122917    # The Hobbit: The Battle of the Five Armies (2014)
    sync_mode: sync
    collection_mode: show_items
    collection_order: release
    
    url_poster: https://raw.githubusercontent.com/Kometa-Team/Default-Images/master/universe/middle.jpg
    # url_background: 

  #Star Wars Universe*:
    #sort_title: "!040_Star Wars Universe*"
    #imdb_list:
      #list_id: ls501373412
    #sync_mode: sync
    #collection_mode: show_items
    #collection_order: release

    #url_poster: https://api.mediux.pro/assets/60209ad6-d0a8-4d55-a42a-ec0e9e1de3ae
    #url_background: https://api.mediux.pro/assets/a70c2519-7180-4b59-854b-742af7bf4ad2

  View Askewniverse*:
    sort_title: "!040_View Askewniverse*"
    tmdb_movie:
      - 2292      # Clerks (1994)
      - 2293      # Mallrats (1995)
      - 2255      # Chasing Amy (1997)
      - 1832      # Dogma (1999)
      - 2294      # Jay and Silent Bob Strike Back (2001)
      - 2295      # Clerks II (2006)
      - 179267    # Jay & Silent Bob's Super Groovy Cartoon Movie! (2013)
      - 440762    # Jay and Silent Bob Reboot (2019)
      - 635891    # Clerks III (2022)
    sync_mode: sync
    collection_mode: show_items
    collection_order: release

    url_poster: https://raw.githubusercontent.com/Kometa-Team/Default-Images/master/universe/askew.jpg
    # url_background:

  Wizarding World*:
    sort_title: "!040_Wizarding World*"
    tmdb_movie:
      - 671       # Harry Potter and the Sorcerer's Stone (2001)
      - 672       # Harry Potter and the Chamber of Secrets (2002)
      - 673       # Harry Potter and the Prisoner of Azkaban (2004)
      - 674       # Harry Potter and the Goblet of Fire (2005)
      - 675       # Harry Potter and the Order of the Phoenix (2007)
      - 767       # Harry Potter and the Half-Blood Prince (2009)
      - 12444     # Harry Potter and the Deathly Hallows: Part 1 (2010)
      - 12445     # Harry Potter and the Deathly Hallows: Part 2 (2011)
      - 259316    # Fantastic Beasts and Where to Find Them (2016)
      - 338952    # Fantastic Beasts: The Crimes of Grindelwald (2018)
      - 338953    # Fantastic Beasts: The Secrets of Dumbledore (2022)
    sync_mode: sync
    collection_mode: show_items
    collection_order: release

    url_poster: https://raw.githubusercontent.com/Kometa-Team/Default-Images/master/universe/wizard.jpg
    # url_background:
    
  X-Men Universe*:
    sort_title: "!040_X-Men Universe*"
    tmdb_movie:
      - 36657     # X-Men (2000)
      - 36658     # X2: X-Men United (2003)
      - 36668     # X-Men: The Last Stand (2006)
      - 2080      # X-Men Origins: Wolverine (2009)
      - 49538     # X-Men: First Class (2011)
      - 76170     # The Wolverine (2013)
      - 127585    # X-Men: Days of Future Past (2014)
      - 293660    # Deadpool (2016)
      - 246655    # X-Men: Apocalypse (2016)
      - 263115    # Logan (2017)
      - 383498    # Deadpool 2 (2018)
      - 320288    # Dark Phoenix (2019)
      - 340102    # The New Mutants (2020)
      - 533535    # Deadpool & Wolverine (2024)
    sync_mode: sync
    collection_mode: show_items
    collection_order: release

    url_poster: https://raw.githubusercontent.com/Kometa-Team/Default-Images/master/universe/xmen.jpg
    # url_background:

  ##################################################
  # Franchises
  ##################################################

  #Fast & Furious*:
    #sort_title: "!050 - Franchise"
    #tmdb_collection: 9485
    #tmdb_movie:
      #- 384018   # Fast & Furious Presents: Hobbs

    #sync_mode: sync
    #collection_mode: show_items
    #collection_order: release
    #url_poster: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/fast-and-furious/poster.jpg
    #url_background: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/collections/movies/fast-and-furious/fanart.jpg
