collections:

  ##################################################
  # Marvel Television Universe
  ##################################################

  Marvel Cinematic Universe:
    sort_title: "!20 - Universe"

    imdb_list:
      list_id: ls539646485

    tmdb_show:
      - 138503   # Your Friendly Neighborhood Spider-Man (2025)
      - 232125   # I Am Groot (2022)
      - 241388   # Eyes of Wakanda (2025)
      - 138505   # Marvel Zombies (2025)
      - 213375   # VisionQuest (2026)
      - 69088    # Agents of S.H.I.E.L.D.: Slingshot (2016)

    sync_mode: sync
    collection_mode: show_items
    collection_order: release

    url_poster: https://raw.githubusercontent.com/kingmsj28/kometa-collections/main/assets/collections/tv-collections/Marvel-Television.png
    # url_background:

  ##################################################
  # Dexter Collection
  ##################################################

  Dexter Collection:
    sort_title: "!30 - Franchise"

    tmdb_show:
      - 1405      # Dexter (2006)
      - 131927    # Dexter: New Blood (2021)
      - 219937    # Dexter: Original Sin (2024)
      - 259909    # Dexter: Resurrection (2025)

    sync_mode: sync
    collection_mode: show_items
    collection_order: release

    url_poster: https://raw.githubusercontent.com/kingmsj28/kometa-collections/main/assets/collections/tv-collections/Dexter-Collection.png
    # url_background:

  ##################################################
  # Breaking Bad Collection
  ##################################################

  Breaking Bad Collection:
    sort_title: "!30 - Franchise"

    tmdb_show:
      - 1396      # Breaking Bad (2008)
      - 60059     # Better Call Saul (2015)

    sync_mode: sync
    collection_mode: show_items
    collection_order: release

    url_poster: https://raw.githubusercontent.com/kingmsj28/kometa-collections/main/assets/collections/tv-collections/Breaking-Bad-Collection.png
    # url_background:

  ##################################################
  # Vought Cinematic Universe
  ##################################################

  Vought Cinematic Universe:
    sort_title: "!20 - Universe"

    tmdb_show:
      - 76479     # The Boys (2019)
      - 205715    # Gen V (2023)
      - 119279    # The Boys Presents: Diabolical (2022)

    sync_mode: sync
    collection_mode: show_items
    collection_order: release

    url_poster: https://raw.githubusercontent.com/kingmsj28/kometa-collections/main/assets/collections/tv-collections/VCU.png
    # url_background:


  ##################################################
  # World of Ice and Fire
  ##################################################

  World of Ice and Fire:
    sort_title: "!30 - Franchise"

    tmdb_show:
      - 1399      # Game of Thrones (2011)
      - 94997     # House of the Dragon (2022)

    sync_mode: sync
    collection_mode: show_items
    collection_order: release

    url_poster: https://raw.githubusercontent.com/kingmsj28/kometa-collections/main/assets/collections/tv-collections/World-of-Ice-and-Fire.png
    # url_background:

  ##################################################
  # WWE Collection
  ##################################################

  WWE Collection:
    sort_title: "!30 - Franchise"

    tmdb_show:
      - 4656      # WWE Raw (1993)
      - 1549      # WWE SmackDown (1999)
      - 31991     # WWE NXT (2010)
      - 289485    # WWE: Unreal (2025)

    sync_mode: sync
    collection_mode: show_items
    collection_order: release

    url_poster: https://raw.githubusercontent.com/kingmsj28/kometa-collections/main/assets/collections/tv-collections/WWE TV/WWETV.png
    url_background: https://raw.githubusercontent.com/kingmsj28/kometa-collections/main/assets/collections/tv-collections/WWE TV/WWETVfanart.png
