metadata:

  1218925: # Chainsaw Man - The Movie: Reze Arc (2025)
    url_poster: https://theposterdb.com/api/assets/567746

  11299: # Cowboy Bebop: The Movie (2001)
    url_poster: https://theposterdb.com/api/assets/520221

  635302: # Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train (2020)
    url_poster: https://api.mediux.pro/assets/7ff14245-a01a-40c2-898d-be7cc8112e10

  1311031: # Demon Slayer: Kimetsu no Yaiba Infinity Castle (2025)
    url_poster: https://api.mediux.pro/assets/5de16038-e414-4b1d-84c3-b7b133b374f1

  39144: # Dragon Ball: Curse of the Blood Rubies (1986)
    url_poster: https://theposterdb.com/api/assets/445208

  39145: # Dragon Ball: Sleeping Princess in Devil's Castle (1987)
    url_poster: https://theposterdb.com/api/assets/445210

  116776: # Dragon Ball: Mystical Adventure (1988)
    url_poster: https://theposterdb.com/api/assets/445211

  39148: # Dragon Ball: The Path to Power (1996)
    url_poster: https://theposterdb.com/api/assets/445213

  38594: # Dragon Ball: Yo! Son Goku and His Friends Return!! (2008)
    url_poster: https://theposterdb.com/api/assets/445180

  120475: # Dragon Ball: Episode of Bardock (2011)
    url_poster: https://theposterdb.com/api/assets/445201

  28609: # Dragon Ball Z: Dead Zone (1989)
    url_poster: https://theposterdb.com/api/assets/445185

  39323: # Dragon Ball Z: Bardock – The Father of Goku (1990)
    url_poster: https://theposterdb.com/api/assets/445188

  39100: # Dragon Ball Z: The World's Strongest (1990)
    url_poster: https://theposterdb.com/api/assets/445186

  39101: # Dragon Ball Z: The Tree of Might (1990)
    url_poster: https://theposterdb.com/api/assets/445187

  24752: # Dragon Ball Z: Cooler's Revenge (1991)
    url_poster: https://theposterdb.com/api/assets/445190

  39102: # Dragon Ball Z: Lord Slug (1991)
    url_poster: https://theposterdb.com/api/assets/445189

  39103: # Dragon Ball Z: The Return of Cooler (1992)
    url_poster: https://theposterdb.com/api/assets/445191

  39104: # Dragon Ball Z: Super Android 13! (1992)
    url_poster: https://theposterdb.com/api/assets/445192

  34433: # Dragon Ball Z: Broly – The Legendary Super Saiyan (1993)
    url_poster: https://theposterdb.com/api/assets/445194

  39105: # Dragon Ball Z: Bojack Unbound (1993)
    url_poster: https://theposterdb.com/api/assets/445195

  39324: # Dragon Ball Z: The History of Trunks (1993)
    url_poster: https://theposterdb.com/api/assets/445193

  44251: # Dragon Ball Z: Broly – Second Coming (1994)
    url_poster: https://theposterdb.com/api/assets/445175

  39106: # Dragon Ball Z: Bio-Broly (1994)
    url_poster: https://theposterdb.com/api/assets/445176

  39107: # Dragon Ball Z: Fusion Reborn (1995)
    url_poster: https://theposterdb.com/api/assets/445177

  39108: # Dragon Ball Z: Wrath of the Dragon (1995)
    url_poster: https://theposterdb.com/api/assets/445178

  89636: # Dragon Ball Z: Plan to Eradicate the Super Saiyans (2010)
    url_poster: https://theposterdb.com/api/assets/445174

  126963: # Dragon Ball Z: Battle of Gods (2013)
    url_poster: https://theposterdb.com/api/assets/445202

  303857: # Dragon Ball Z: Resurrection 'F' (2015)
    url_poster: https://theposterdb.com/api/assets/445182

  18095: # Dragon Ball GT: A Hero's Legacy (1997)
    url_poster: https://theposterdb.com/api/assets/445200

  503314: # Dragon Ball Super: Broly (2018)
    url_poster: https://theposterdb.com/api/assets/445162

  610150: # Dragon Ball Super: Super Hero (2022)
    url_poster: https://theposterdb.com/api/assets/445163

  652754: # Dragon Ball Z Side Story: Plan to Eradicate the Saiyans (1993)
    url_poster: https://theposterdb.com/api/assets/687935
