collections:

  ##################################################
  # Chainsaw Man
  ##################################################

  Chainsaw Man:
    tmdb_movie:
      - 1218925   # Chainsaw Man - The Movie: Reze Arc (2025)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/567743
    
  ##################################################
  # Cowboy Bebop
  ##################################################

  Cowboy Bebop:
    tmdb_movie:
      - 11299   # Cowboy Bebop: The Movie (2001)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://api.mediux.pro/assets/a0dbf36c-c41f-41f1-b172-9f19c2987f70
    
  ##################################################
  # Demon Slayer
  ##################################################

  Demon Slayer:
    tmdb_movie:
      - 635302    # Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train (2020)
      - 1311031   # Demon Slayer: Kimetsu no Yaiba Infinity Castle (2025)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/31955

  ##################################################
  # Dragon Ball Universe
  ##################################################

  Dragon Ball Universe:
    sort_title: "Dragon Ball 00"
    tmdb_movie:
      - 39144    # Dragon Ball: Curse of the Blood Rubies (1986)
      - 39145    # Dragon Ball: Sleeping Princess in Devil's Castle (1987)
      - 116776   # Dragon Ball: Mystical Adventure (1988)
      - 39148    # Dragon Ball: The Path to Power (1996)
      - 38594    # Dragon Ball: Yo! Son Goku and His Friends Return!! (2008)
      - 120475   # Dragon Ball: Episode of Bardock (2011)
      - 28609    # Dragon Ball Z: Dead Zone (1989)
      - 39323    # Dragon Ball Z: Bardock – The Father of Goku (1990)
      - 39100    # Dragon Ball Z: The World's Strongest (1990)
      - 39101    # Dragon Ball Z: The Tree of Might (1990)
      - 24752    # Dragon Ball Z: Cooler's Revenge (1991)
      - 39102    # Dragon Ball Z: Lord Slug (1991)
      - 39103    # Dragon Ball Z: The Return of Cooler (1992)
      - 39104    # Dragon Ball Z: Super Android 13! (1992)
      - 34433    # Dragon Ball Z: Broly – The Legendary Super Saiyan (1993)
      - 39105    # Dragon Ball Z: Bojack Unbound (1993)
      - 39324    # Dragon Ball Z: The History of Trunks (1993)
      - 652754   # Dragon Ball Z Side Story: Plan to Eradicate the Saiyans (1993)
      - 44251    # Dragon Ball Z: Broly – Second Coming (1994)
      - 39106    # Dragon Ball Z: Bio-Broly (1994)
      - 39107    # Dragon Ball Z: Fusion Reborn (1995)
      - 39108    # Dragon Ball Z: Wrath of the Dragon (1995)
      - 89636     # Dragon Ball Z: Plan to Eradicate the Super Saiyans (2010)
      - 126963   # Dragon Ball Z: Battle of Gods (2013)
      - 303857   # Dragon Ball Z: Resurrection 'F' (2015)
      - 18095    # Dragon Ball GT: A Hero's Legacy (1997)
      - 503314   # Dragon Ball Super: Broly (2018)
      - 610150   # Dragon Ball Super: Super Hero (2022)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://api.mediux.pro/assets/2dca7a85-04cb-4ec1-b10c-d9191327bd14

  ##################################################
  # Dragon Ball
  ##################################################

  Dragon Ball:
    sort_title: "Dragon Ball 01"
    tmdb_movie:
      - 39144    # Dragon Ball: Curse of the Blood Rubies (1986)
      - 39145    # Dragon Ball: Sleeping Princess in Devil's Castle (1987)
      - 116776   # Dragon Ball: Mystical Adventure (1988)
      - 39148    # Dragon Ball: The Path to Power (1996)
      - 38594    # Dragon Ball: Yo! Son Goku and His Friends Return!! (2008)
      - 120475   # Dragon Ball: Episode of Bardock (2011)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/445206

  ##################################################
  # Dragon Ball Z
  ##################################################

  Dragon Ball Z:
    sort_title: "Dragon Ball 02"
    tmdb_movie:
      - 28609    # Dragon Ball Z: Dead Zone (1989)
      - 39323    # Dragon Ball Z: Bardock – The Father of Goku (1990)
      - 39100    # Dragon Ball Z: The World's Strongest (1990)
      - 39101    # Dragon Ball Z: The Tree of Might (1990)
      - 24752    # Dragon Ball Z: Cooler's Revenge (1991)
      - 39102    # Dragon Ball Z: Lord Slug (1991)
      - 39103    # Dragon Ball Z: The Return of Cooler (1992)
      - 39104    # Dragon Ball Z: Super Android 13! (1992)
      - 34433    # Dragon Ball Z: Broly – The Legendary Super Saiyan (1993)
      - 39105    # Dragon Ball Z: Bojack Unbound (1993)
      - 39324    # Dragon Ball Z: The History of Trunks (1993)
      - 652754   # Dragon Ball Z Side Story: Plan to Eradicate the Saiyans (1993)
      - 44251    # Dragon Ball Z: Broly – Second Coming (1994)
      - 39106    # Dragon Ball Z: Bio-Broly (1994)
      - 39107    # Dragon Ball Z: Fusion Reborn (1995)
      - 39108    # Dragon Ball Z: Wrath of the Dragon (1995)
      - 89636      # Dragon Ball Z: Plan to Eradicate the Super Saiyans (2010)
      - 126963   # Dragon Ball Z: Battle of Gods (2013)
      - 303857   # Dragon Ball Z: Resurrection 'F' (2015)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/445184

  ##################################################
  # Dragon Ball GT
  ##################################################

  Dragon Ball GT:
    sort_title: "Dragon Ball 03"
    tmdb_movie:
      - 18095    # Dragon Ball GT: A Hero's Legacy (1997)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/444521

  ##################################################
  # Dragon Ball Super
  ##################################################

  Dragon Ball Super:
    sort_title: "Dragon Ball 04"
    tmdb_movie:
      - 503314   # Dragon Ball Super: Broly (2018)
      - 610150   # Dragon Ball Super: Super Hero (2022)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/445161