metadata:

  ##################################################
  # Chainsaw Man
  ##################################################

  1218925: # Chainsaw Man - The Movie: Reze Arc (2025)
    url_poster: https://theposterdb.com/api/assets/567746
    
  ##################################################
  # Cowboy Bebop
  ##################################################

  11299: # Cowboy Bebop: The Movie (2001)
    url_poster: https://theposterdb.com/api/assets/520221