collections:

  ##################################################
  # Chainsaw Man
  ##################################################

  Chainsaw Man:
    tvdb_show:
      - 397934   # Chainsaw Man (2022)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/567743
    
  ##################################################
  # Cowboy Bebop
  ##################################################

  Cowboy Bebop:
    tvdb_show:
      - 76885   # Cowboy Bebop (1998)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://api.mediux.pro/assets/a0dbf36c-c41f-41f1-b172-9f19c2987f70
    
  ##################################################
  # Demon Slayer
  ##################################################

  Demon Slayer:
    tvdb_show:
      - 348545   # Demon Slayer: Kimetsu no Yaiba (2019)
    collection_mode: hide
    collection_order: release
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/31955