overlays:

  Airing:
    overlay:
      name: airing
      url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/overlays/tv-status/airing_small.png
      group: STATUS
      weight: 950
    tmdb_on_the_air: 2000
    filters:
      label: Art*

  Returning:
    overlay:
      name: returning
      url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/overlays/tv-status/returning_small.png
      group: STATUS
      weight: 800
    plex_all: true
    filters:
      label: Art*
      tmdb_status:
        - returning
        - planned
        - production

  Ended:
    overlay:
      name: ended
      url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/overlays/tv-status/ended_small.png
      group: STATUS
      weight: 700
    plex_all: true
    filters:
      label: Art*
      tmdb_status:
        - ended
        - canceled

  Canceled:
    overlay:
      name: canceled
      url: https://raw.githubusercontent.com/kingmsj28/plex-kometa/main/assets/overlays/tv-status/canceled_small.png
      group: STATUS
      weight: 750
    plex_all: true
    filters:
      label: Art*
      tmdb_status: canceled
      last_episode_aired: 365